<a href="https://colab.research.google.com/github/nikki-nikitha17/python_practice_nikki/blob/main/da_assessment_67f9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import re

In [2]:
df =pd.read_csv("/content/car_price_performance.csv")

In [3]:
df.head()

     Brand  Price  Horsepower  Fuel Efficiency
0  Brand C  91942         382             15.3
1  Brand A  70075         197             32.6
2  Brand C  84524         188             34.9
3  Brand E  68939         258             15.1
4  Brand X  66505         277             13.0

In [4]:
df.shape

(2000, 4)

In [5]:
dfnoprice = df[df['Price'].isna()]
dfnoprice

Empty DataFrame
Columns: [Brand, Price, Horsepower, Fuel Efficiency]
Index: []

In [6]:
dfnocompany = df[df['Brand'].isna()]
dfnocompany

Empty DataFrame
Columns: [Brand, Price, Horsepower, Fuel Efficiency]
Index: []

In [10]:
brand_avg_prices = df.groupby("Brand")["Price"].mean().sort_values(ascending=False)
brand_avg_prices.count()
brand_avg_prices

Brand
Brand D    65498.701681
Brand X    65405.884259
Brand Z    65244.331818
Brand C    64707.967890
Brand B    64686.641350
Brand A    64224.495370
Brand Y    63880.171569
Brand E    63712.542601
Brand W    63034.557018
Name: Price, dtype: float64

In [8]:
d={}
for i in brand_avg_prices.index:
  print(i)

Brand D
Brand X
Brand Z
Brand C
Brand B
Brand A
Brand Y
Brand E
Brand W

In [17]:
d = {}
j=len(brand_avg_prices)
for i in brand_avg_prices.index:
  d[i] = j
  j-=1
d

{'Brand D': 9,
 'Brand X': 8,
 'Brand Z': 7,
 'Brand C': 6,
 'Brand B': 5,
 'Brand A': 4,
 'Brand Y': 3,
 'Brand E': 2,
 'Brand W': 1}

In [19]:
x=[]
for j in df['Brand']:
  y=d[j]
  x.append(y)
df['encoded_brand']=x
df

        Brand  Price  Horsepower  Fuel Efficiency  encoded_brand
0     Brand C  91942         382             15.3              6
1     Brand A  70075         197             32.6              4
2     Brand C  84524         188             34.9              6
3     Brand E  68939         258             15.1              2
4     Brand X  66505         277             13.0              8
...       ...    ...         ...              ...            ...
1995  Brand Z  34535         196             15.2              7
1996  Brand C  35215         377             25.3              6
1997  Brand E  72980         294             21.8              2
1998  Brand Z  55921         443             11.0              7
1999  Brand B  95051         225             12.4              5

[2000 rows x 5 columns]

In [23]:
scaled_fuel_efficieny=[]
min=df['Fuel Efficiency'].min()
max=df['Fuel Efficiency'].max()
for i in df['Fuel Efficiency']:
  scaled_value=(i-min)/(max-min)
  scaled_fuel_efficieny.append(scaled_value)
df['scaled_fuel_efficieny']=scaled_fuel_efficieny
df

,Brand,Price,Horsepower,Fuel Efficiency,encoded_brand,scaled_fuel_efficieny,scaled_horsepower
0,Brand C,91942,382,15.3,6,0.212,0.7050
1,Brand A,70075,197,32.6,4,0.904,0.2425
2,Brand C,84524,188,34.9,6,0.996,0.2200
3,Brand E,68939,258,15.1,2,0.204,0.3950
4,Brand X,66505,277,13.0,8,0.120,0.4425
...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.208,0.2400
1996,Brand C,35215,377,25.3,6,0.612,0.6925
1997,Brand E,72980,294,21.8,2,0.472,0.4850
1998,Brand Z,55921,443,11.0,7,0.040,0.8575
1999,Brand B,95051,225,12.4,5,0.096,0.3125

In [24]:
scaled_horsepower=[]
min=df['Horsepower'].min()
max=df['Horsepower'].max()
for i in df['Horsepower']:
  scaled_value=(i-min)/(max-min)
  scaled_horsepower.append(scaled_value)
df['scaled_horsepower']=scaled_horsepower
df

,Brand,Price,Horsepower,Fuel Efficiency,encoded_brand,scaled_fuel_efficieny,scaled_horsepower
0,Brand C,91942,382,15.3,6,0.212,0.7050
1,Brand A,70075,197,32.6,4,0.904,0.2425
2,Brand C,84524,188,34.9,6,0.996,0.2200
3,Brand E,68939,258,15.1,2,0.204,0.3950
4,Brand X,66505,277,13.0,8,0.120,0.4425
...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.208,0.2400
1996,Brand C,35215,377,25.3,6,0.612,0.6925
1997,Brand E,72980,294,21.8,2,0.472,0.4850
1998,Brand Z,55921,443,11.0,7,0.040,0.8575
1999,Brand B,95051,225,12.4,5,0.096,0.3125

In [25]:
scaled_encoded_brand=[]
min=df['encoded_brand'].min()
max=df['encoded_brand'].max()
for i in df['encoded_brand']:
  scaled_value=(i-min)/(max-min)
  scaled_encoded_brand.append(scaled_value)
df['scaled_encoded_brand']=scaled_encoded_brand
df

,Brand,Price,Horsepower,Fuel Efficiency,encoded_brand,scaled_fuel_efficieny,scaled_horsepower,scaled_encoded_brand
0,Brand C,91942,382,15.3,6,0.212,0.7050,0.625
1,Brand A,70075,197,32.6,4,0.904,0.2425,0.375
2,Brand C,84524,188,34.9,6,0.996,0.2200,0.625
3,Brand E,68939,258,15.1,2,0.204,0.3950,0.125
4,Brand X,66505,277,13.0,8,0.120,0.4425,0.875
...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.208,0.2400,0.750
1996,Brand C,35215,377,25.3,6,0.612,0.6925,0.625
1997,Brand E,72980,294,21.8,2,0.472,0.4850,0.125
1998,Brand Z,55921,443,11.0,7,0.040,0.8575,0.750
1999,Brand B,95051,225,12.4,5,0.096,0.3125,0.500

In [26]:
df['Performance_Index'] = (df['Horsepower'] * 0.7 + df['Fuel Efficiency'] * 0.3) / df['Price']
df

,Brand,Price,Horsepower,Fuel Efficiency,encoded_brand,scaled_fuel_efficieny,scaled_horsepower,scaled_encoded_brand,Performance_Index
0,Brand C,91942,382,15.3,6,0.212,0.7050,0.625,0.002958
1,Brand A,70075,197,32.6,4,0.904,0.2425,0.375,0.002107
2,Brand C,84524,188,34.9,6,0.996,0.2200,0.625,0.001681
3,Brand E,68939,258,15.1,2,0.204,0.3950,0.125,0.002685
4,Brand X,66505,277,13.0,8,0.120,0.4425,0.875,0.002974
...,...,...,...,...,...,...,...,...,...
1995,Brand Z,34535,196,15.2,7,0.208,0.2400,0.750,0.004105
1996,Brand C,35215,377,25.3,6,0.612,0.6925,0.625,0.007709
1997,Brand E,72980,294,21.8,2,0.472,0.4850,0.125,0.002910
1998,Brand Z,55921,443,11.0,7,0.040,0.8575,0.750,0.005604
1999,Brand B,95051,225,12.4,5,0.096,0.3125,0.500,0.001696

In [28]:
df.to_csv('23ag1a67f9.csv', index=False)